=== VamsiThutikuntaRepo/FebTibco/TibcoFeb/SharedResources/Schema/UserSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	 xmlns="http://www.tibco.com/schemas/TibcoFeb/SharedResources/Schema/Schema.xsd"
	 targetNamespace="http://www.tibco.com/schemas/TibcoFeb/SharedResources/Schema/Schema.xsd"
	 elementFormDefault="qualified"
	 attributeFormDefault="unqualified">
	<xs:element name="Usersinfo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Userdata" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Userdata">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="UserID"/>
				<xs:element ref="UserName"/>
				<xs:element ref="UserDesignation"/>
				<xs:element ref="UserCity"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="UserID" type="xs:string"/>
	<xs:element name="UserName" type="xs:string"/>
	<xs:element name="UserDesignation" type="xs:string"/>
	<xs:element name="UserCity" type="xs:string"/>
</xs:schema>

=== VamsiThutikuntaRepo/FebTibco/TibcoFeb/Files/Usersinfo.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<Usersinfo xmlns = "http://www.tibco.com/schemas/TibcoFeb/SharedResources/Schema/Schema.xsd" xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation = "http://www.tibco.com/schemas/TibcoFeb/SharedResources/Schema/Schema.xsd UserSchema.xsd">
	<Userdata>
		<UserID>322333</UserID>
		<UserName>Vamsi</UserName>
		<UserDesignation>Software Engineer</UserDesignation>
		<UserCity>Jrg</UserCity>
	</Userdata>
	<Userdata>
		<UserID>723456</UserID>
		<UserName>Chaitanya</UserName>
		<UserDesignation>Software Developer</UserDesignation>
		<UserCity>Vizag</UserCity>
	</Userdata>
	<Userdata>
		<UserID>128734</UserID>
		<UserName>Teja</UserName>
		<UserDesignation>Engineer</UserDesignation>
		<UserCity>Vizag</UserCity>
	</Userdata>
	<Userdata>
		<UserID>545443</UserID>
		<UserName>Srinath</UserName>
		<UserDesignation>Solution Engineer</UserDesignation>
		<UserCity>Nellore</UserCity>
	</Userdata>
</Usersinfo>
